### ISSUE TITLE
ZeroDivisionError for teams that have no matches in a series

### ISSUE THREAD

**Issue by ReagentX** [sublee/glicko2#3]
If a team has no matches in a series, Glicko2().rate() returns `ZeroDivisionError` since `variance_inv` never gets set to something other than zero. This means that teams with 0 matches will not get decayed.

**Comment by drdarina** [comment]
According to the [paper](http://www.glicko.net/glicko/glicko2.pdf) in this case you only compute step 6: `phi_star`. Agree that it's missing in the code.

**Comment by Dakkers** [comment]
this has been fixed right?

commit: https://github.com/sublee/glicko2/commit/99285aa6b5250b91a837b842dc61b2a96007f3c5#diff-d262ec5f69c9f38c308b361f71fbc41d

**Comment by ReagentX** [comment]
Looks like it.
